---
apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-credentials
  namespace: logging
type: Opaque
stringData:
  elasticsearch-url: "https://798a3a233ea341aaad5b6c044a95fb25.us-central1.gcp.cloud.es.io:443"
  elasticsearch-api-key: "NUFZeHlwY0JBTWFEMkZxbV96M0g6QnZHN3hPYWZJRlZLcG92UnVzbmVEQQ=="
  # Base64 encoded API key for HTTP headers
  elasticsearch-api-key-b64: "QXBpS2V5IE5VRlplSGx3WTBKQlRXRkVNa1p4YlY5Nk0wZzZRblpITjNoUFlXWkpSbFpMY0c5MlVuVnpibVZFUVE9PQ=="
---
apiVersion: v1
kind: Namespace
metadata:
  name: logging
  labels:
    name: logging
  annotations:
    consul.hashicorp.com/connect-inject: "false" 