---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluent-bit
  namespace: logging
  labels:
    app: fluent-bit
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluent-bit
  labels:
    app: fluent-bit
rules:
- apiGroups: [""]
  resources:
    - namespaces
    - pods
    - pods/logs
    - nodes
    - nodes/proxy
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluent-bit
  labels:
    app: fluent-bit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluent-bit
subjects:
- kind: ServiceAccount
  name: fluent-bit
  namespace: logging
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: logging
  labels:
    app: fluent-bit
    version: v1
spec:
  selector:
    matchLabels:
      app: fluent-bit
  template:
    metadata:
      labels:
        app: fluent-bit
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "2020"
        prometheus.io/path: "/api/v1/metrics/prometheus"
        consul.hashicorp.com/connect-inject: "false"
    spec:
      serviceAccountName: fluent-bit
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      - operator: "Exists"
        effect: "NoExecute"  
      - operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: fluent-bit
        image: fluent/fluent-bit:3.0.7
        imagePullPolicy: Always
        ports:
        - containerPort: 2020
          name: http-metrics
          protocol: TCP
        env:
        - name: FLUENT_CONF
          value: /fluent-bit/etc/fluent-bit.conf
        - name: CLUSTER_NAME
          value: "dev-eks-us-east-2"  # This should be dynamic per cluster
        - name: ENVIRONMENT
          value: "dev"
        - name: CLOUD_PROVIDER
          value: "aws"  # This should be dynamic per cluster
        - name: REGION
          value: "us-east-2"  # This should be dynamic per cluster
        - name: ELASTICSEARCH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: elasticsearch-credentials
              key: elasticsearch-api-key
        resources:
          limits:
            memory: 200Mi
            cpu: 200m
          requests:
            memory: 100Mi
            cpu: 100m
        volumeMounts:
        - name: config
          mountPath: /fluent-bit/etc
        - name: varlog
          mountPath: /var/log
          readOnly: true
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: fluent-bit-db
          mountPath: /var/log/flb-storage/
        - name: systemd-log
          mountPath: /run/log
          readOnly: true
        livenessProbe:
          httpGet:
            path: /
            port: 2020
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/v1/health
            port: 2020
          initialDelaySeconds: 30
          periodSeconds: 10
      terminationGracePeriodSeconds: 30
      volumes:
      - name: config
        configMap:
          name: fluent-bit-config
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: fluent-bit-db
        hostPath:
          path: /var/log/flb-storage
          type: DirectoryOrCreate
      - name: systemd-log
        hostPath:
          path: /run/log
---
# Service for Prometheus metrics scraping
apiVersion: v1
kind: Service
metadata:
  name: fluent-bit-metrics
  namespace: logging
  labels:
    app: fluent-bit
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "2020"
    prometheus.io/path: "/api/v1/metrics/prometheus"
spec:
  type: ClusterIP
  ports:
  - name: http-metrics
    port: 2020
    targetPort: 2020
    protocol: TCP
  selector:
    app: fluent-bit
---
# ServiceMonitor for Prometheus Operator
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fluent-bit
  namespace: logging
  labels:
    app: fluent-bit
spec:
  selector:
    matchLabels:
      app: fluent-bit
  endpoints:
  - port: http-metrics
    path: /api/v1/metrics/prometheus
    interval: 30s
    scrapeTimeout: 10s 