# AWS S3 Backend Configuration
# Generated by bootstrap process

terraform {
  backend "s3" {
    bucket         = "${bucket}"
    key            = "terraform.tfstate"
    region         = "${region}"
    dynamodb_table = "${dynamodb_table}"
    encrypt        = true
  }
}