# CircleCI Integration with Nexus Repository Manager
# Add this to your .circleci/config.yml

version: 2.1

orbs:
  nexus: # Custom orb for Nexus integration

executors:
  nexus-enabled:
    docker:
      - image: cimg/node:18.17
    environment:
      NEXUS_URL: http://k8s-nexusdev-nexusext-6e81eefea8-b22d7349bfce6095.elb.us-east-2.amazonaws.com:8081
      NPM_REGISTRY: http://k8s-nexusdev-nexusext-6e81eefea8-b22d7349bfce6095.elb.us-east-2.amazonaws.com:8081/repository/npm-proxy/
      PYPI_INDEX_URL: http://k8s-nexusdev-nexusext-6e81eefea8-b22d7349bfce6095.elb.us-east-2.amazonaws.com:8081/repository/pypi-proxy/simple

jobs:
  build-with-nexus:
    executor: nexus-enabled
    steps:
      - checkout
      
      # Configure NPM to use Nexus proxy
      - run:
          name: Configure NPM Registry
          command: |
            echo "ðŸ”§ Configuring NPM to use Nexus proxy cache"
            npm config set registry $NPM_REGISTRY
            npm config set strict-ssl false  # For dev environment
            
      # Configure Python/pip to use Nexus
      - run:
          name: Configure Python Dependencies
          command: |
            echo "ðŸ Configuring pip to use Nexus PyPI proxy"
            mkdir -p ~/.pip
            cat > ~/.pip/pip.conf << EOL
            [global]
            index-url = $PYPI_INDEX_URL
            trusted-host = $(echo $PYPI_INDEX_URL | cut -d'/' -f3 | cut -d':' -f1)
            EOL
            
      # Build with dependency caching through Nexus
      - run:
          name: Install Dependencies via Nexus
          command: |
            echo "ðŸ“¦ Installing dependencies through Nexus cache"
            npm install
            
      # Push build metadata to Prometheus (as per architecture)
      - run:
          name: Report Build Metrics
          command: |
            echo "ðŸ“Š Pushing build metadata to Prometheus"
            curl -X POST http://prometheus-pushgateway:9091/metrics/job/circleci-build/instance/$CIRCLE_BUILD_NUM \
              --data-binary @- << EOF
            # Build completion metrics
            circleci_build_duration_seconds{job="$CIRCLE_JOB",status="success"} $(date +%s)
            circleci_dependencies_cached{registry="nexus"} 1
            EOF

workflows:
  build-and-deploy:
    jobs:
      - build-with-nexus:
          context: nexus-integration
