# JFrog Artifactory Image Pull Secret Template
# This creates docker registry credentials for pulling images from JFrog
---
apiVersion: v1
kind: Secret
metadata:
  name: jfrog-pull-secret
  namespace: frontend-dev
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: |
    ${JFROG_DOCKER_CONFIG_JSON_BASE64}
---
apiVersion: v1
kind: Secret
metadata:
  name: jfrog-pull-secret
  namespace: backend-dev
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: |
    ${JFROG_DOCKER_CONFIG_JSON_BASE64}
---
apiVersion: v1
kind: Secret
metadata:
  name: jfrog-pull-secret
  namespace: observability
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: |
    ${JFROG_DOCKER_CONFIG_JSON_BASE64} 