goal: Configure security findings integration with logging pipeline
steps:
- name: Review security integration config
  type: prompt
  prompt: Examine the security findings integration YAML to understand how security
    events are collected.
- name: Configure security scanners
  type: prompt
  prompt: Setup integration with security scanning tools (Falco, OPA, etc.) for runtime
    security monitoring.
- name: Setup alert rules
  type: prompt
  prompt: Configure alerting rules for critical security findings with appropriate
    severity thresholds.
- name: Apply security integration
  type: cli
  command: kubectl apply -f k8s/envs/dev/logging/security-findings-integration.yaml

