# Root Terragrunt configuration
# This file is inherited by all environments

# Local variables for backend configuration  
locals {
  # Parse the path to get environment and region
  path_parts = split("/", path_relative_to_include())
  # Expect path structure envs/<env>/<region>
  environment = local.path_parts[1]
  region      = local.path_parts[2]
  
  # Backend bucket name - dynamically generated by bootstrap
  backend_bucket = "complex-demo-tfstate-jyv43s"
  backend_region = "us-east-2"
  backend_dynamodb_table = "complex-demo-tfstate-locks"
}

# Configure S3 backend
remote_state {
  backend = "s3"
  
  generate = {
    path      = "backend.tf"
    if_exists = "overwrite_terragrunt"
  }
  
  config = {
    bucket         = local.backend_bucket
    key            = "${local.environment}/${local.region}/terraform.tfstate"
    region         = local.backend_region
    dynamodb_table = local.backend_dynamodb_table
    encrypt        = true
  }
}

# Generate provider configurations
generate "providers" {
  path      = "providers.tf"
  if_exists = "overwrite_terragrunt"
  
  contents = <<EOT
terraform {
  required_version = ">= 1.5.0"
  
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
    google = {
      source  = "hashicorp/google"
      version = "~> 5.0"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.0"
    }
    helm = {
      source  = "hashicorp/helm"
      version = "~> 2.0"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.0"
    }
    tls = {
      source  = "hashicorp/tls"
      version = "~> 4.0"
    }
    external = {
      source  = "hashicorp/external"
      version = "~> 2.0"
    }
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.0"
    }
  }
}

# AWS Provider Configuration
provider "aws" {
  region = var.aws_region
  profile = "sandbox-permanent"
  
  default_tags {
    tags = var.common_tags
  }
}

# GCP Provider Configuration
provider "google" {
  project = var.gcp_project_id
  region  = var.gcp_region
}

# Azure Provider Configuration
provider "azurerm" {
  features {}
  
  # Uses currently authenticated subscription from 'az login'
}
EOT
}

# Common variables
inputs = {
  # Environment will be set by child terragrunt.hcl files
  # Region will be set by child terragrunt.hcl files
  
  # Common tags applied to all resources
  common_tags = {}
}
