---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: datadog-cluster-agent-aws
  namespace: datadog
  labels:
    app: datadog-cluster-agent
    cloud: aws
    team: observability
spec:
  selector:
    matchLabels:
      app: datadog-cluster-agent
  endpoints:
  - port: agentmetrics
    interval: 30s
    path: /metrics
    scheme: http
    honorLabels: true
    metricRelabelings:
    - sourceLabels: [__name__]
      regex: 'datadog_(.+)'
      targetLabel: __name__
      replacement: 'dd_${1}'
    - sourceLabels: [cluster_name]
      targetLabel: k8s_cluster
    - sourceLabels: []
      targetLabel: cloud_provider
      replacement: 'aws'
    - sourceLabels: []
      targetLabel: monitoring_source
      replacement: 'datadog'
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: datadog-cluster-agent-gcp
  namespace: datadog
  labels:
    app: datadog-cluster-agent
    cloud: gcp
    team: observability
spec:
  selector:
    matchLabels:
      app: datadog-cluster-agent
      cloud: gcp
  endpoints:
  - port: agentmetrics
    interval: 30s
    path: /metrics
    scheme: http
    honorLabels: true
    metricRelabelings:
    - sourceLabels: [__name__]
      regex: 'datadog_(.+)'
      targetLabel: __name__
      replacement: 'dd_${1}'
    - sourceLabels: [cluster_name]
      targetLabel: k8s_cluster
    - sourceLabels: []
      targetLabel: cloud_provider
      replacement: 'gcp'
    - sourceLabels: []
      targetLabel: monitoring_source
      replacement: 'datadog'
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: datadog-cluster-agent-azure
  namespace: datadog
  labels:
    app: datadog-cluster-agent
    cloud: azure
    team: observability
spec:
  selector:
    matchLabels:
      app: datadog-cluster-agent
      cloud: azure
  endpoints:
  - port: agentmetrics
    interval: 30s
    path: /metrics
    scheme: http
    honorLabels: true
    metricRelabelings:
    - sourceLabels: [__name__]
      regex: 'datadog_(.+)'
      targetLabel: __name__
      replacement: 'dd_${1}'
    - sourceLabels: [cluster_name]
      targetLabel: k8s_cluster
    - sourceLabels: []
      targetLabel: cloud_provider
      replacement: 'azure'
    - sourceLabels: []
      targetLabel: monitoring_source
      replacement: 'datadog' 