apiVersion: v1
kind: Service
metadata:
  name: nexus-metrics
  namespace: nexus-dev
  labels:
    app: nexus3
    prometheus.io/scrape: "true"
    prometheus.io/port: "8081"
    prometheus.io/path: "/service/metrics/prometheus"
spec:
  selector:
    app.kubernetes.io/name: nexus3
    app.kubernetes.io/instance: nexus-repo
  ports:
  - name: metrics
    port: 8081
    targetPort: 8081
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nexus-servicemonitor
  namespace: nexus-dev
  labels:
    app: nexus3
spec:
  selector:
    matchLabels:
      prometheus.io/scrape: "true"
  endpoints:
  - port: metrics
    path: /service/metrics/prometheus
    interval: 30s
    scrapeTimeout: 10s
