---
# Puppet Integration Playbook
# Architecture Plan: "Tower playbook triggers Puppet runs via REST API at the end of provisioning"
# Key Interaction: "Tower writes a classification Hiera file consumed by Puppet for ongoing policy"

- name: Upload Hiera Classifications to Puppet Enterprise
  hosts: puppet_servers
  become: yes
  gather_facts: yes
  
  vars:
    hiera_data_dir: "/tmp/hiera-classifications"
    puppet_hiera_dir: "/etc/puppetlabs/code/environments/production/data/nodes"
    puppet_api_url: "https://{{ ansible_host }}:8140"
    puppet_console_url: "https://{{ ansible_host }}"
    
  tasks:
    - name: Display Puppet Enterprise information
      debug:
        msg: |
          Uploading Hiera classifications to Puppet Enterprise
          Server: {{ ansible_host }}
          Hiera Directory: {{ puppet_hiera_dir }}
          API URL: {{ puppet_api_url }}
    
    - name: Ensure Puppet hiera directory exists
      file:
        path: "{{ puppet_hiera_dir }}"
        state: directory
        owner: pe-puppet
        group: pe-puppet
        mode: '0755'
        
    - name: Upload node classification files to Puppet
      copy:
        src: "{{ hiera_data_dir }}/{{ item }}.yaml"
        dest: "{{ puppet_hiera_dir }}/{{ item }}.yaml"
        owner: pe-puppet
        group: pe-puppet
        mode: '0644'
      loop: "{{ groups['day0_provisioning'] | default([]) | difference(groups['kubernetes_clusters'] | default([])) }}"
      when: groups['day0_provisioning'] is defined
      notify: refresh puppet environment
      
    - name: Create node classification script
      template:
        src: puppet-node-classifier.j2
        dest: /opt/puppetlabs/bin/puppet-node-classifier
        owner: root
        group: root
        mode: '0755'
        
    - name: Configure hiera.yaml for node-specific data
      template:
        src: hiera.yaml.j2
        dest: /etc/puppetlabs/code/environments/production/hiera.yaml
        owner: pe-puppet
        group: pe-puppet
        mode: '0644'
      notify: refresh puppet environment

  handlers:
    - name: refresh puppet environment
      command: /opt/puppetlabs/bin/puppet-code deploy production --wait
      become_user: pe-puppet

- name: Trigger Puppet Runs via REST API
  hosts: localhost
  gather_facts: no
  
  vars:
    puppet_server: "{{ hostvars[groups['puppet_servers'][0]]['ansible_host'] if groups['puppet_servers'] is defined and groups['puppet_servers'] | length > 0 else '' }}"
    puppet_console_url: "https://{{ puppet_server }}"
    puppet_orchestrator_url: "https://{{ puppet_server }}:8143"
    
  tasks:
    - name: Wait for Puppet Enterprise to be ready
      uri:
        url: "{{ puppet_console_url }}/status/v1/simple"
        method: GET
        validate_certs: no
        timeout: 30
      register: puppet_status
      until: puppet_status.status == 200
      retries: 10
      delay: 30
      when: puppet_server != ""
      
    - name: Get Puppet access token
      uri:
        url: "{{ puppet_console_url }}:4433/rbac-api/v1/auth/token"
        method: POST
        body_format: json
        body:
          login: "admin"
          password: "{{ puppet_admin_password | default('admin') }}"
          lifetime: "1h"
        validate_certs: no
        status_code: 200
      register: puppet_token
      when: puppet_server != ""
      ignore_errors: yes
      
    - name: Display token acquisition status
      debug:
        msg: |
          Puppet token acquisition: {{ 'Success' if puppet_token.status == 200 else 'Failed' }}
          {% if puppet_token.status != 200 %}
          Error: {{ puppet_token.msg | default('Unknown error') }}
          {% endif %}
      when: puppet_server != ""
      
    - name: Trigger Puppet runs for provisioned nodes
      uri:
        url: "{{ puppet_orchestrator_url }}/orchestrator/v1/command/deploy"
        method: POST
        headers:
          X-Authentication: "{{ puppet_token.json.token }}"
          Content-Type: "application/json"
        body_format: json
        body:
          environment: "production"
          scope:
            nodes:
{% for host in groups['day0_provisioning'] | default([]) | difference(groups['kubernetes_clusters'] | default([])) %}
              - "{{ host }}.{{ hostvars[host]['ansible_domain'] | default('local') }}"
{% endfor %}
          concurrency: 5
          enforce_environment: true
        validate_certs: no
        status_code: 202
      register: puppet_job
      when: puppet_server != "" and puppet_token.status == 200
      ignore_errors: yes
      
    - name: Display Puppet job status
      debug:
        msg: |
          Puppet orchestration job: {{ 'Started' if puppet_job.status == 202 else 'Failed' }}
          {% if puppet_job.status == 202 %}
          Job ID: {{ puppet_job.json.job.id }}
          {% else %}
          Error: {{ puppet_job.msg | default('Failed to trigger Puppet runs') }}
          {% endif %}
      when: puppet_server != ""
      
    # Alternative: Direct puppet agent run trigger for nodes that can't use orchestrator
    - name: Trigger direct Puppet agent runs (fallback)
      command: "ssh -o StrictHostKeyChecking=no {{ hostvars[item]['ansible_user'] }}@{{ hostvars[item]['ansible_host'] }} 'sudo /opt/puppetlabs/bin/puppet agent -t'"
      loop: "{{ groups['day0_provisioning'] | default([]) | difference(groups['kubernetes_clusters'] | default([])) }}"
      when: 
        - puppet_server != ""
        - puppet_token.status != 200 or puppet_job.status != 202
        - hostvars[item]['day_2_ops'] | default(false)
      ignore_errors: yes
      delegate_to: localhost
      
    - name: Generate Puppet integration summary
      debug:
        msg: |
          🎉 Puppet Integration Completed!
          
          📋 Summary:
          - Hiera classifications uploaded: {{ (groups['day0_provisioning'] | default([]) | difference(groups['kubernetes_clusters'] | default([]))) | length }} nodes
          - Puppet server: {{ puppet_server }}
          - Console URL: {{ puppet_console_url }}
          - Orchestrator URL: {{ puppet_orchestrator_url }}
          
          📊 Next Steps:
          1. Monitor Puppet runs in the PE Console: {{ puppet_console_url }}
          2. Check node status: https://{{ puppet_server }}/nodes
          3. Review reports: https://{{ puppet_server }}/reports
          
          🔄 Day-2 Operations:
          - Puppet agents will run every 30 minutes
          - Configuration drift will be automatically remediated
          - Reports will be exported to Elasticsearch
          
          Architecture compliance: ✅ 
          - Tower writes Hiera classification files ✅
          - Puppet consumes node-specific data ✅  
          - REST API triggers Puppet runs ✅
          - Day-2 drift remediation enabled ✅ 