# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "complex-demo-tfstate-c61tvk"
    dynamodb_table = "complex-demo-tfstate-locks"
    encrypt        = true
    key            = "envs/dev/terraform.tfstate"
    region         = "us-east-1"
  }
}
