apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 5.51.6
    helm:
      values: |
        global:
          image:
            tag: v2.8.4
        
        server:
          replicas: 3
          service:
            type: LoadBalancer
          ingress:
            enabled: true
            ingressClassName: aws-load-balancer
            annotations:
              kubernetes.io/ingress.class: alb
              alb.ingress.kubernetes.io/scheme: internet-facing
              alb.ingress.kubernetes.io/target-type: ip
          
        repoServer:
          replicas: 2
          
        applicationSet:
          enabled: true
          replicas: 2
          
        controller:
          replicas: 1
          
        redis-ha:
          enabled: true
          replicas: 3
          
        configs:
          repositories: |
            - type: git
              url: https://github.com/Panchangam18/complex-demo
              name: infrastructure
            - type: helm
              url: https://argoproj.github.io/argo-helm
              name: argo
            - type: helm
              url: https://charts.jetstack.io
              name: jetstack
            - type: helm
              url: https://prometheus-community.github.io/helm-charts
              name: prometheus-community
              
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 