---
apiVersion: v1
kind: Namespace
metadata:
  name: datadog
  labels:
    name: datadog
  annotations:
    consul.hashicorp.com/connect-inject: "false"
---
apiVersion: v1
kind: Secret
metadata:
  name: datadog-credentials
  namespace: datadog
type: Opaque
stringData:
  api-key: "af3cb41c927647ee8b56794caf9fdb4d"
  app-key: "a046dd9ca1becba27a2ec4d3b357fad53655b813"
---
# Additional secret for cluster-specific configuration
apiVersion: v1
kind: Secret
metadata:
  name: datadog-cluster-agent
  namespace: datadog
type: Opaque
stringData:
  token: "datadog-cluster-agent-token-dev-multicloud-2024" 