---
apiVersion: v1
kind: Namespace
metadata:
  name: datadog
  labels:
    name: datadog
  annotations:
    consul.hashicorp.com/connect-inject: "false"
---
apiVersion: v1
kind: Secret
metadata:
  name: datadog-credentials
  namespace: datadog
type: Opaque
stringData:
  api-key: "${DATADOG_API_KEY}"
  app-key: "${DATADOG_APP_KEY}"
---
# Additional secret for cluster-specific configuration
apiVersion: v1
kind: Secret
metadata:
  name: datadog-cluster-agent
  namespace: datadog
type: Opaque
stringData:
  token: "datadog-cluster-agent-token-dev-multicloud-2024" 